//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientBookingRoom.RoomServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueTupleOfBooleanStringStringInt32", Namespace="http://yourdomain.com/")]
    [System.SerializableAttribute()]
    public partial class ValueTupleOfBooleanStringStringInt32 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool Item1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item3Field;
        
        private int Item4Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Item1 {
            get {
                return this.Item1Field;
            }
            set {
                if ((this.Item1Field.Equals(value) != true)) {
                    this.Item1Field = value;
                    this.RaisePropertyChanged("Item1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Item2 {
            get {
                return this.Item2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item2Field, value) != true)) {
                    this.Item2Field = value;
                    this.RaisePropertyChanged("Item2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Item3 {
            get {
                return this.Item3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item3Field, value) != true)) {
                    this.Item3Field = value;
                    this.RaisePropertyChanged("Item3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Item4 {
            get {
                return this.Item4Field;
            }
            set {
                if ((this.Item4Field.Equals(value) != true)) {
                    this.Item4Field = value;
                    this.RaisePropertyChanged("Item4");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://yourdomain.com/")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RoomIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNameField;
        
        private int CapacityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RoomID {
            get {
                return this.RoomIDField;
            }
            set {
                if ((this.RoomIDField.Equals(value) != true)) {
                    this.RoomIDField = value;
                    this.RaisePropertyChanged("RoomID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoomName {
            get {
                return this.RoomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNameField, value) != true)) {
                    this.RoomNameField = value;
                    this.RaisePropertyChanged("RoomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingDetails", Namespace="http://yourdomain.com/")]
    [System.SerializableAttribute()]
    public partial class BookingDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime BookingDateField;
        
        private int RoomIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNameField;
        
        private System.DateTime StartTimeField;
        
        private System.DateTime EndTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime BookingDate {
            get {
                return this.BookingDateField;
            }
            set {
                if ((this.BookingDateField.Equals(value) != true)) {
                    this.BookingDateField = value;
                    this.RaisePropertyChanged("BookingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RoomID {
            get {
                return this.RoomIDField;
            }
            set {
                if ((this.RoomIDField.Equals(value) != true)) {
                    this.RoomIDField = value;
                    this.RaisePropertyChanged("RoomID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RoomName {
            get {
                return this.RoomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNameField, value) != true)) {
                    this.RoomNameField = value;
                    this.RaisePropertyChanged("RoomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://yourdomain.com/", ConfigurationName="RoomServiceReference.RoomServiceSoap")]
    public interface RoomServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://yourdomain.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/Login", ReplyAction="*")]
        ClientBookingRoom.RoomServiceReference.LoginResponse Login(ClientBookingRoom.RoomServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.LoginResponse> LoginAsync(ClientBookingRoom.RoomServiceReference.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://yourdomain.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/ForgotPassword", ReplyAction="*")]
        ClientBookingRoom.RoomServiceReference.ForgotPasswordResponse ForgotPassword(ClientBookingRoom.RoomServiceReference.ForgotPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/ForgotPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.ForgotPasswordResponse> ForgotPasswordAsync(ClientBookingRoom.RoomServiceReference.ForgotPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name GetListRoomResult from namespace http://yourdomain.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/GetListRoom", ReplyAction="*")]
        ClientBookingRoom.RoomServiceReference.GetListRoomResponse GetListRoom(ClientBookingRoom.RoomServiceReference.GetListRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/GetListRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.GetListRoomResponse> GetListRoomAsync(ClientBookingRoom.RoomServiceReference.GetListRoomRequest request);
        
        // CODEGEN: Generating message contract since element name GetBookingDetailsResult from namespace http://yourdomain.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/GetBookingDetails", ReplyAction="*")]
        ClientBookingRoom.RoomServiceReference.GetBookingDetailsResponse GetBookingDetails(ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/GetBookingDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.GetBookingDetailsResponse> GetBookingDetailsAsync(ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name staffID from namespace http://yourdomain.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/BookingRoom", ReplyAction="*")]
        ClientBookingRoom.RoomServiceReference.BookingRoomResponse BookingRoom(ClientBookingRoom.RoomServiceReference.BookingRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/BookingRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.BookingRoomResponse> BookingRoomAsync(ClientBookingRoom.RoomServiceReference.BookingRoomRequest request);
        
        // CODEGEN: Generating message contract since element name staffID from namespace http://yourdomain.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/CancelBooking", ReplyAction="*")]
        ClientBookingRoom.RoomServiceReference.CancelBookingResponse CancelBooking(ClientBookingRoom.RoomServiceReference.CancelBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/CancelBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.CancelBookingResponse> CancelBookingAsync(ClientBookingRoom.RoomServiceReference.CancelBookingRequest request);
        
        // CODEGEN: Generating message contract since element name newPassword from namespace http://yourdomain.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/ChangePassword", ReplyAction="*")]
        ClientBookingRoom.RoomServiceReference.ChangePasswordResponse ChangePassword(ClientBookingRoom.RoomServiceReference.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.ChangePasswordResponse> ChangePasswordAsync(ClientBookingRoom.RoomServiceReference.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name oldPassword from namespace http://yourdomain.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/VerifyPassword", ReplyAction="*")]
        ClientBookingRoom.RoomServiceReference.VerifyPasswordResponse VerifyPassword(ClientBookingRoom.RoomServiceReference.VerifyPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/VerifyPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.VerifyPasswordResponse> VerifyPasswordAsync(ClientBookingRoom.RoomServiceReference.VerifyPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name staffID from namespace http://yourdomain.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/EditRoom", ReplyAction="*")]
        ClientBookingRoom.RoomServiceReference.EditRoomResponse EditRoom(ClientBookingRoom.RoomServiceReference.EditRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourdomain.com/EditRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.EditRoomResponse> EditRoomAsync(ClientBookingRoom.RoomServiceReference.EditRoomRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ClientBookingRoom.RoomServiceReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ClientBookingRoom.RoomServiceReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientBookingRoom.RoomServiceReference.ValueTupleOfBooleanStringStringInt32 LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(ClientBookingRoom.RoomServiceReference.ValueTupleOfBooleanStringStringInt32 LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ForgotPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ForgotPassword", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.ForgotPasswordRequestBody Body;
        
        public ForgotPasswordRequest() {
        }
        
        public ForgotPasswordRequest(ClientBookingRoom.RoomServiceReference.ForgotPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class ForgotPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public ForgotPasswordRequestBody() {
        }
        
        public ForgotPasswordRequestBody(string username, string email) {
            this.username = username;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ForgotPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ForgotPasswordResponse", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.ForgotPasswordResponseBody Body;
        
        public ForgotPasswordResponse() {
        }
        
        public ForgotPasswordResponse(ClientBookingRoom.RoomServiceReference.ForgotPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class ForgotPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ForgotPasswordResult;
        
        public ForgotPasswordResponseBody() {
        }
        
        public ForgotPasswordResponseBody(string ForgotPasswordResult) {
            this.ForgotPasswordResult = ForgotPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListRoom", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.GetListRoomRequestBody Body;
        
        public GetListRoomRequest() {
        }
        
        public GetListRoomRequest(ClientBookingRoom.RoomServiceReference.GetListRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListRoomRequestBody {
        
        public GetListRoomRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListRoomResponse", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.GetListRoomResponseBody Body;
        
        public GetListRoomResponse() {
        }
        
        public GetListRoomResponse(ClientBookingRoom.RoomServiceReference.GetListRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class GetListRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientBookingRoom.RoomServiceReference.Room[] GetListRoomResult;
        
        public GetListRoomResponseBody() {
        }
        
        public GetListRoomResponseBody(ClientBookingRoom.RoomServiceReference.Room[] GetListRoomResult) {
            this.GetListRoomResult = GetListRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookingDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookingDetails", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequestBody Body;
        
        public GetBookingDetailsRequest() {
        }
        
        public GetBookingDetailsRequest(ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class GetBookingDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime bookingDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int roomID;
        
        public GetBookingDetailsRequestBody() {
        }
        
        public GetBookingDetailsRequestBody(int staffID, System.DateTime bookingDate, int roomID) {
            this.staffID = staffID;
            this.bookingDate = bookingDate;
            this.roomID = roomID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookingDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookingDetailsResponse", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.GetBookingDetailsResponseBody Body;
        
        public GetBookingDetailsResponse() {
        }
        
        public GetBookingDetailsResponse(ClientBookingRoom.RoomServiceReference.GetBookingDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class GetBookingDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientBookingRoom.RoomServiceReference.BookingDetails[] GetBookingDetailsResult;
        
        public GetBookingDetailsResponseBody() {
        }
        
        public GetBookingDetailsResponseBody(ClientBookingRoom.RoomServiceReference.BookingDetails[] GetBookingDetailsResult) {
            this.GetBookingDetailsResult = GetBookingDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookingRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookingRoom", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.BookingRoomRequestBody Body;
        
        public BookingRoomRequest() {
        }
        
        public BookingRoomRequest(ClientBookingRoom.RoomServiceReference.BookingRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class BookingRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int roomID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime bookingDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string shift;
        
        public BookingRoomRequestBody() {
        }
        
        public BookingRoomRequestBody(string staffID, int roomID, System.DateTime bookingDate, string shift) {
            this.staffID = staffID;
            this.roomID = roomID;
            this.bookingDate = bookingDate;
            this.shift = shift;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookingRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookingRoomResponse", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.BookingRoomResponseBody Body;
        
        public BookingRoomResponse() {
        }
        
        public BookingRoomResponse(ClientBookingRoom.RoomServiceReference.BookingRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class BookingRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool BookingRoomResult;
        
        public BookingRoomResponseBody() {
        }
        
        public BookingRoomResponseBody(bool BookingRoomResult) {
            this.BookingRoomResult = BookingRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelBooking", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.CancelBookingRequestBody Body;
        
        public CancelBookingRequest() {
        }
        
        public CancelBookingRequest(ClientBookingRoom.RoomServiceReference.CancelBookingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class CancelBookingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int roomID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime bookingDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string shift;
        
        public CancelBookingRequestBody() {
        }
        
        public CancelBookingRequestBody(string staffID, int roomID, System.DateTime bookingDate, string shift) {
            this.staffID = staffID;
            this.roomID = roomID;
            this.bookingDate = bookingDate;
            this.shift = shift;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelBookingResponse", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.CancelBookingResponseBody Body;
        
        public CancelBookingResponse() {
        }
        
        public CancelBookingResponse(ClientBookingRoom.RoomServiceReference.CancelBookingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class CancelBookingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CancelBookingResult;
        
        public CancelBookingResponseBody() {
        }
        
        public CancelBookingResponseBody(bool CancelBookingResult) {
            this.CancelBookingResult = CancelBookingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(ClientBookingRoom.RoomServiceReference.ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newPassword;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(int staffID, string newPassword) {
            this.staffID = staffID;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(ClientBookingRoom.RoomServiceReference.ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class ChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponseBody() {
        }
        
        public ChangePasswordResponseBody(bool ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyPassword", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.VerifyPasswordRequestBody Body;
        
        public VerifyPasswordRequest() {
        }
        
        public VerifyPasswordRequest(ClientBookingRoom.RoomServiceReference.VerifyPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class VerifyPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        public VerifyPasswordRequestBody() {
        }
        
        public VerifyPasswordRequestBody(int staffID, string oldPassword) {
            this.staffID = staffID;
            this.oldPassword = oldPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyPasswordResponse", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.VerifyPasswordResponseBody Body;
        
        public VerifyPasswordResponse() {
        }
        
        public VerifyPasswordResponse(ClientBookingRoom.RoomServiceReference.VerifyPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class VerifyPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyPasswordResult;
        
        public VerifyPasswordResponseBody() {
        }
        
        public VerifyPasswordResponseBody(bool VerifyPasswordResult) {
            this.VerifyPasswordResult = VerifyPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditRoom", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.EditRoomRequestBody Body;
        
        public EditRoomRequest() {
        }
        
        public EditRoomRequest(ClientBookingRoom.RoomServiceReference.EditRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class EditRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int roomID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string roomName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string capacity;
        
        public EditRoomRequestBody() {
        }
        
        public EditRoomRequestBody(string staffID, int roomID, string roomName, string capacity) {
            this.staffID = staffID;
            this.roomID = roomID;
            this.roomName = roomName;
            this.capacity = capacity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditRoomResponse", Namespace="http://yourdomain.com/", Order=0)]
        public ClientBookingRoom.RoomServiceReference.EditRoomResponseBody Body;
        
        public EditRoomResponse() {
        }
        
        public EditRoomResponse(ClientBookingRoom.RoomServiceReference.EditRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourdomain.com/")]
    public partial class EditRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditRoomResult;
        
        public EditRoomResponseBody() {
        }
        
        public EditRoomResponseBody(bool EditRoomResult) {
            this.EditRoomResult = EditRoomResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RoomServiceSoapChannel : ClientBookingRoom.RoomServiceReference.RoomServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomServiceSoapClient : System.ServiceModel.ClientBase<ClientBookingRoom.RoomServiceReference.RoomServiceSoap>, ClientBookingRoom.RoomServiceReference.RoomServiceSoap {
        
        public RoomServiceSoapClient() {
        }
        
        public RoomServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBookingRoom.RoomServiceReference.LoginResponse ClientBookingRoom.RoomServiceReference.RoomServiceSoap.Login(ClientBookingRoom.RoomServiceReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public ClientBookingRoom.RoomServiceReference.ValueTupleOfBooleanStringStringInt32 Login(string username, string password) {
            ClientBookingRoom.RoomServiceReference.LoginRequest inValue = new ClientBookingRoom.RoomServiceReference.LoginRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ClientBookingRoom.RoomServiceReference.LoginResponse retVal = ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.LoginResponse> ClientBookingRoom.RoomServiceReference.RoomServiceSoap.LoginAsync(ClientBookingRoom.RoomServiceReference.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.LoginResponse> LoginAsync(string username, string password) {
            ClientBookingRoom.RoomServiceReference.LoginRequest inValue = new ClientBookingRoom.RoomServiceReference.LoginRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBookingRoom.RoomServiceReference.ForgotPasswordResponse ClientBookingRoom.RoomServiceReference.RoomServiceSoap.ForgotPassword(ClientBookingRoom.RoomServiceReference.ForgotPasswordRequest request) {
            return base.Channel.ForgotPassword(request);
        }
        
        public string ForgotPassword(string username, string email) {
            ClientBookingRoom.RoomServiceReference.ForgotPasswordRequest inValue = new ClientBookingRoom.RoomServiceReference.ForgotPasswordRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.ForgotPasswordRequestBody();
            inValue.Body.username = username;
            inValue.Body.email = email;
            ClientBookingRoom.RoomServiceReference.ForgotPasswordResponse retVal = ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).ForgotPassword(inValue);
            return retVal.Body.ForgotPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.ForgotPasswordResponse> ClientBookingRoom.RoomServiceReference.RoomServiceSoap.ForgotPasswordAsync(ClientBookingRoom.RoomServiceReference.ForgotPasswordRequest request) {
            return base.Channel.ForgotPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.ForgotPasswordResponse> ForgotPasswordAsync(string username, string email) {
            ClientBookingRoom.RoomServiceReference.ForgotPasswordRequest inValue = new ClientBookingRoom.RoomServiceReference.ForgotPasswordRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.ForgotPasswordRequestBody();
            inValue.Body.username = username;
            inValue.Body.email = email;
            return ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).ForgotPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBookingRoom.RoomServiceReference.GetListRoomResponse ClientBookingRoom.RoomServiceReference.RoomServiceSoap.GetListRoom(ClientBookingRoom.RoomServiceReference.GetListRoomRequest request) {
            return base.Channel.GetListRoom(request);
        }
        
        public ClientBookingRoom.RoomServiceReference.Room[] GetListRoom() {
            ClientBookingRoom.RoomServiceReference.GetListRoomRequest inValue = new ClientBookingRoom.RoomServiceReference.GetListRoomRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.GetListRoomRequestBody();
            ClientBookingRoom.RoomServiceReference.GetListRoomResponse retVal = ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).GetListRoom(inValue);
            return retVal.Body.GetListRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.GetListRoomResponse> ClientBookingRoom.RoomServiceReference.RoomServiceSoap.GetListRoomAsync(ClientBookingRoom.RoomServiceReference.GetListRoomRequest request) {
            return base.Channel.GetListRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.GetListRoomResponse> GetListRoomAsync() {
            ClientBookingRoom.RoomServiceReference.GetListRoomRequest inValue = new ClientBookingRoom.RoomServiceReference.GetListRoomRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.GetListRoomRequestBody();
            return ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).GetListRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBookingRoom.RoomServiceReference.GetBookingDetailsResponse ClientBookingRoom.RoomServiceReference.RoomServiceSoap.GetBookingDetails(ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequest request) {
            return base.Channel.GetBookingDetails(request);
        }
        
        public ClientBookingRoom.RoomServiceReference.BookingDetails[] GetBookingDetails(int staffID, System.DateTime bookingDate, int roomID) {
            ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequest inValue = new ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.bookingDate = bookingDate;
            inValue.Body.roomID = roomID;
            ClientBookingRoom.RoomServiceReference.GetBookingDetailsResponse retVal = ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).GetBookingDetails(inValue);
            return retVal.Body.GetBookingDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.GetBookingDetailsResponse> ClientBookingRoom.RoomServiceReference.RoomServiceSoap.GetBookingDetailsAsync(ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequest request) {
            return base.Channel.GetBookingDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.GetBookingDetailsResponse> GetBookingDetailsAsync(int staffID, System.DateTime bookingDate, int roomID) {
            ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequest inValue = new ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.GetBookingDetailsRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.bookingDate = bookingDate;
            inValue.Body.roomID = roomID;
            return ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).GetBookingDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBookingRoom.RoomServiceReference.BookingRoomResponse ClientBookingRoom.RoomServiceReference.RoomServiceSoap.BookingRoom(ClientBookingRoom.RoomServiceReference.BookingRoomRequest request) {
            return base.Channel.BookingRoom(request);
        }
        
        public bool BookingRoom(string staffID, int roomID, System.DateTime bookingDate, string shift) {
            ClientBookingRoom.RoomServiceReference.BookingRoomRequest inValue = new ClientBookingRoom.RoomServiceReference.BookingRoomRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.BookingRoomRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.roomID = roomID;
            inValue.Body.bookingDate = bookingDate;
            inValue.Body.shift = shift;
            ClientBookingRoom.RoomServiceReference.BookingRoomResponse retVal = ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).BookingRoom(inValue);
            return retVal.Body.BookingRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.BookingRoomResponse> ClientBookingRoom.RoomServiceReference.RoomServiceSoap.BookingRoomAsync(ClientBookingRoom.RoomServiceReference.BookingRoomRequest request) {
            return base.Channel.BookingRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.BookingRoomResponse> BookingRoomAsync(string staffID, int roomID, System.DateTime bookingDate, string shift) {
            ClientBookingRoom.RoomServiceReference.BookingRoomRequest inValue = new ClientBookingRoom.RoomServiceReference.BookingRoomRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.BookingRoomRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.roomID = roomID;
            inValue.Body.bookingDate = bookingDate;
            inValue.Body.shift = shift;
            return ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).BookingRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBookingRoom.RoomServiceReference.CancelBookingResponse ClientBookingRoom.RoomServiceReference.RoomServiceSoap.CancelBooking(ClientBookingRoom.RoomServiceReference.CancelBookingRequest request) {
            return base.Channel.CancelBooking(request);
        }
        
        public bool CancelBooking(string staffID, int roomID, System.DateTime bookingDate, string shift) {
            ClientBookingRoom.RoomServiceReference.CancelBookingRequest inValue = new ClientBookingRoom.RoomServiceReference.CancelBookingRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.CancelBookingRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.roomID = roomID;
            inValue.Body.bookingDate = bookingDate;
            inValue.Body.shift = shift;
            ClientBookingRoom.RoomServiceReference.CancelBookingResponse retVal = ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).CancelBooking(inValue);
            return retVal.Body.CancelBookingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.CancelBookingResponse> ClientBookingRoom.RoomServiceReference.RoomServiceSoap.CancelBookingAsync(ClientBookingRoom.RoomServiceReference.CancelBookingRequest request) {
            return base.Channel.CancelBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.CancelBookingResponse> CancelBookingAsync(string staffID, int roomID, System.DateTime bookingDate, string shift) {
            ClientBookingRoom.RoomServiceReference.CancelBookingRequest inValue = new ClientBookingRoom.RoomServiceReference.CancelBookingRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.CancelBookingRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.roomID = roomID;
            inValue.Body.bookingDate = bookingDate;
            inValue.Body.shift = shift;
            return ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).CancelBookingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBookingRoom.RoomServiceReference.ChangePasswordResponse ClientBookingRoom.RoomServiceReference.RoomServiceSoap.ChangePassword(ClientBookingRoom.RoomServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public bool ChangePassword(int staffID, string newPassword) {
            ClientBookingRoom.RoomServiceReference.ChangePasswordRequest inValue = new ClientBookingRoom.RoomServiceReference.ChangePasswordRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.ChangePasswordRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.newPassword = newPassword;
            ClientBookingRoom.RoomServiceReference.ChangePasswordResponse retVal = ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).ChangePassword(inValue);
            return retVal.Body.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.ChangePasswordResponse> ClientBookingRoom.RoomServiceReference.RoomServiceSoap.ChangePasswordAsync(ClientBookingRoom.RoomServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.ChangePasswordResponse> ChangePasswordAsync(int staffID, string newPassword) {
            ClientBookingRoom.RoomServiceReference.ChangePasswordRequest inValue = new ClientBookingRoom.RoomServiceReference.ChangePasswordRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.ChangePasswordRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.newPassword = newPassword;
            return ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBookingRoom.RoomServiceReference.VerifyPasswordResponse ClientBookingRoom.RoomServiceReference.RoomServiceSoap.VerifyPassword(ClientBookingRoom.RoomServiceReference.VerifyPasswordRequest request) {
            return base.Channel.VerifyPassword(request);
        }
        
        public bool VerifyPassword(int staffID, string oldPassword) {
            ClientBookingRoom.RoomServiceReference.VerifyPasswordRequest inValue = new ClientBookingRoom.RoomServiceReference.VerifyPasswordRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.VerifyPasswordRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.oldPassword = oldPassword;
            ClientBookingRoom.RoomServiceReference.VerifyPasswordResponse retVal = ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).VerifyPassword(inValue);
            return retVal.Body.VerifyPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.VerifyPasswordResponse> ClientBookingRoom.RoomServiceReference.RoomServiceSoap.VerifyPasswordAsync(ClientBookingRoom.RoomServiceReference.VerifyPasswordRequest request) {
            return base.Channel.VerifyPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.VerifyPasswordResponse> VerifyPasswordAsync(int staffID, string oldPassword) {
            ClientBookingRoom.RoomServiceReference.VerifyPasswordRequest inValue = new ClientBookingRoom.RoomServiceReference.VerifyPasswordRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.VerifyPasswordRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.oldPassword = oldPassword;
            return ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).VerifyPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBookingRoom.RoomServiceReference.EditRoomResponse ClientBookingRoom.RoomServiceReference.RoomServiceSoap.EditRoom(ClientBookingRoom.RoomServiceReference.EditRoomRequest request) {
            return base.Channel.EditRoom(request);
        }
        
        public bool EditRoom(string staffID, int roomID, string roomName, string capacity) {
            ClientBookingRoom.RoomServiceReference.EditRoomRequest inValue = new ClientBookingRoom.RoomServiceReference.EditRoomRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.EditRoomRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.roomID = roomID;
            inValue.Body.roomName = roomName;
            inValue.Body.capacity = capacity;
            ClientBookingRoom.RoomServiceReference.EditRoomResponse retVal = ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).EditRoom(inValue);
            return retVal.Body.EditRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.EditRoomResponse> ClientBookingRoom.RoomServiceReference.RoomServiceSoap.EditRoomAsync(ClientBookingRoom.RoomServiceReference.EditRoomRequest request) {
            return base.Channel.EditRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBookingRoom.RoomServiceReference.EditRoomResponse> EditRoomAsync(string staffID, int roomID, string roomName, string capacity) {
            ClientBookingRoom.RoomServiceReference.EditRoomRequest inValue = new ClientBookingRoom.RoomServiceReference.EditRoomRequest();
            inValue.Body = new ClientBookingRoom.RoomServiceReference.EditRoomRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.roomID = roomID;
            inValue.Body.roomName = roomName;
            inValue.Body.capacity = capacity;
            return ((ClientBookingRoom.RoomServiceReference.RoomServiceSoap)(this)).EditRoomAsync(inValue);
        }
    }
}
